//
//  AddFavoriteProductsRequest.swift
//
//  File Generated by victor on 08/11/2017.
//  Using model_gen.py
//

import ObjectMapper

class AddFavoriteProductsRequest: Mappable {

	var products: [String]!

	init() {}

	required init?(map: Map){}

	func mapping(map: Map) {
		products <- map["products"]
	}
}

