//
//  ConversationRequest.swift
//
//  File Generated by yeyo on 09/13/2017.
//  Using model_gen.py
//

import ObjectMapper

class ConversationRequest: Mappable {

	var offer: String!
	var privacy: Int!
	var label: String!
	var purchase_offer: String!
	var user: String!
	var receiver: String!
	var message: ConversationRequest_Message!
	var type: String!

	init() {}

	required init?(map: Map){}

	func mapping(map: Map) {
		offer <- map["offer"]
		privacy <- map["privacy"]
		label <- map["label"]
		purchase_offer <- map["purchase_offer"]
		user <- map["user"]
		receiver <- map["receiver"]
		message <- map["message"]
		type <- map["type"]
	}
}

class ConversationRequest_Message: Mappable {

	var message: String!
	var sender: String?

	init() {}

	required init?(map: Map){}

	func mapping(map: Map) {
		message <- map["message"]
		sender <- map["sender"]
	}
}

