//
//  SaleTemplateInstanceRequest.swift
//
//  File Generated by victor on 07/07/2017.
//  Using model_gen.py
//

import ObjectMapper

class SaleTemplateInstanceRequest: Mappable {

	var offers: [SaleTemplateInstanceRequest_Offers]!
	var market: String!
	var sale_template: String!

	init() {}

	required init?(map: Map){}

	func mapping(map: Map) {
		offers <- map["offers"]
		market <- map["market"]
		sale_template <- map["sale_template"]
	}
}

class SaleTemplateInstanceRequest_Offers: Mappable {

	var price: String!
	var sale_offer_template: String!
	var recipients: [String]!
	var quantity: Int!

	init() {}

	required init?(map: Map){}

	func mapping(map: Map) {
		price <- map["price"]
		sale_offer_template <- map["sale_offer_template"]
		recipients <- map["recipients"]
		quantity <- map["quantity"]
	}
}

