//
//  SignUpRequest.swift
//
//  File Generated by victor on 10/30/2017.
//  Using model_gen.py
//

import ObjectMapper

class SignUpRequest: Mappable {

	var username: String!
	var first_name: String!
	var last_name: String!
	var account_type: Int!
	var country: Int!
	var phone: String!
	var state: Int!
	var password: String!
	var email: String!
	var market: Int!

	init() {}

	required init?(map: Map){}

	func mapping(map: Map) {
		username <- map["username"]
		first_name <- map["first_name"]
		last_name <- map["last_name"]
		account_type <- map["account_type"]
		country <- map["country"]
		phone <- map["phone"]
		state <- map["state"]
		password <- map["password"]
		email <- map["email"]
		market <- map["market"]
	}
}

