//
//  SignUpResponse.swift
//
//  File Generated by victor on 10/30/2017.
//  Using model_gen.py
//

import ObjectMapper

class SignUpResponse: Mappable {

	var user_username: String!
	var user_id: Int!
	var user_email: String!
	var error: String!

	init() {}

	required init?(map: Map){}

	func mapping(map: Map) {
		user_username <- map["user_username"]
		user_id <- map["user_id"]
		user_email <- map["user_email"]
		error <- map["error"]
	}
}

