//
//  SMSResponse.swift
//
//  File Generated by victor on 10/30/2017.
//  Using model_gen.py
//

import ObjectMapper

class SMSResponse: Mappable {

	var smg: String!
	var error: String!

	init() {}

	required init?(map: Map){}

	func mapping(map: Map) {
		smg <- map["smg"]
		error <- map["error"]
	}
}

